#!/bin/bash

source ./lib/functions

clear

MAIN_MENU=("Git" "Installer" )
PRINT_MENU  "MainMenu" "${MAIN_MENU[@]}"
read -p "What will it be?: " MENU_CHOICE

if  [ $MENU_CHOICE == "1" ]; then

#	GIT_PUSH_PULL $DOTFILES
  clear
  GI

elif [ "$MENU_CHOICE" == "2" ]; then

  bash ./installs/_installer.sh

else
  echo Not a valid choice
  ./linux_tools
fi

