#!/bin/bash

# Paths
REPO='/home/kd/repos/.server-tools-new'
BA_M='/home/kd/.aliases/main'
BA_S='/home/kd/.aliases/server'
BA_D='/home/kd/.aliases/docker'

TM='/home/kd/.tmux.conf'
ZH='/home/kd/.zshrc'
VM='/home/kd/.vimrc'
HOME='/home/kd'

# Funcs
function GITPULL () {
  cd $REPO && \
  git pull && \
  yes | cp -f $REPO/dotfiles/$1 $2 && \
  echo "|Pull|>--- $REPO ---> $2 ---<||"
}

function GITPUSH () {
  yes | cp -f $1 $REPO/dotfiles && \
  cd $REPO && \
  git add . && \
  git commit -m "pushed $1 " && \
  git push && \
  echo "|Push|>--- $1 ---> $REPO/dotfiles ---<||"
}

# Main

clear
echo '||======================|'
echo '||---Kensle Dev Tools---|'
echo '||======================|'
echo '||-----[1] Git----------|'
echo '||-----[2] FirstRun-----|'
echo '||======================|'

read localorrepo

if  [ $localorrepo == "1" ]; then
  
  clear
  echo '||================================|'
  echo '||-----[1] Push to remote---------|'
  echo '||-----[2] Pull from remote-------|'
  echo '||================================|'
  read git
  
  if [ "$git" == "1" ]; then

    clear
    echo '||===========================|'
    echo '||---------GIT PUSH----------|'
    echo '||===========================|'
    echo '||------[1] Bash Aliases-----|'
    echo '||------[2] Tmux Conf--------|'
    echo '||------[3] Zshrc------------|'
    echo '||------[4] Vimrc------------|'
    echo '||===========================|'
    read file

    if [ $file == "1" ]; then
      GITPUSH $ALIASES
    elif $file == "2" ]; then
      GITPUSH $TM
    elif [ $file == "3" ]; then
      GITPUSH $ZH
    elif [ $file == "4" ]; then
      GITPUSH $VM
    fi

    exit 1
  elif [ "$git" == "2" ]; then
    clear
    echo '||===========================|'
    echo '||---------GIT PULL----------|'
    echo '||===========================|'
    echo '||------[1] Bash Aliases-----|'
    echo '||------[2] Tmux Conf--------|'
    echo '||------[3] Zshrc------------|'
    echo '||------[4] Vimrc------------|'
    echo '||===========================|'
    read file

    if [ $file == "1" ]; then
      GITPULL '.aliases' $HOME
    elif [ $file == "2" ]; then
      GITPULL '.tmux.conf' $HOME
    elif [ $file == "3" ]; then
      GITPULL .'zshrc' $HOME
    elif [ $file == "4" ]; then
      GITPULL '.vimrc' $HOME
    fi

    exit 1
  fi

elif [ "$localorrepo" == "2" ]; then

  clear
  echo '||==========================|'
  echo '||-----[1] VPS--------------|'
  echo '||-----[2] VPS DOCKER-------|'
  echo '||==========================|'
  read vps

  elif [ "$vps" == "1" ]; then

    sudo bash ./scripts/firstrun
    GITPULL '.aliases' $HOME
    GITPULL '.tmux.conf' $HOME
    GITPULL .'zshrc' $HOME
    GITPULL '.vimrc' $HOME

    exit 1
  elif [ "$vps" == "2" ]; then
    sudo bash ./scripts/firstDocker
    GITPULL '.aliases' $HOME
    GITPULL '.tmux.conf' $HOME
    GITPULL .'zshrc' $HOME
    GITPULL '.vimrc' $HOME

    exit 1
  fi

fi
