#!/bin/bash

source ./scripts/functions

MAIN_MENU=("Git" "FirstRun" "Link SSH" "Gen SSH")
PRINT_MENU "${MAIN_MENU[@]}"
read -p "What will it be?: " MENU_CHOICE

if  [ $MENU_CHOICE == "1" ]; then

	GIT_PUSH_PULL $DOTFILES

elif [ "$MENU_CHOICE" == "2" ]; then
	echo ""			
	read -p "[1]VPS | [2]Docker_VPS: " VPS_CHOICE
	echo ""

  if [ "$VPS_CHOICE" == "1" ]; then
    sudo bash ./scripts/firstrun
  elif [ "$VPS_CHOICE" == "2" ]; then
    sudo bash ./scripts/firstDocker
  fi

elif [ "$MENU_CHOICE" == "3" ]; then
  bash scripts/link-ssh

elif [ "$MENU_CHOICE" == "4" ]; then
  echo "To link SSH"
  echo ""
  echo "run ssh-keygen"
  echo ""
  echo ssh-copy-id username@remote_host
fi
# --------------------------------------------------------------
# clear
# echo '||======================|'
# echo '||---Kensle Dev Tools---|'
# echo '||======================|'
# echo '||-----[1] Git----------|'
# echo '||-----[2] FirstRun-----|'
# echo '||-----[3] Link SSH-----|'
# echo '||-----[4] Gen SSH------|'
# echo '||======================|'
#
# read MENU
# echo ''
# echo ''
# if  [ $MENU == "1" ]; then
#
# 	GIT_PUSH_PULL $DOTFILES
#
# elif [ "$MENU" == "2" ]; then
#
#   clear
#   echo '||==========================|'
#   echo '||-----[1] VPS--------------|'
#   echo '||-----[2] VPS DOCKER-------|'
#   echo '||==========================|'
#   read vps
#
#   if [ "$vps" == "1" ]; then
#
#     sudo bash ./scripts/firstrun
#
#   elif [ "$vps" == "2" ]; then
#
#     sudo bash ./scripts/firstDocker
#
#   fi
#
# elif [ "$MENU" == "3" ]; then
#   bash scripts/link-ssh
#
# elif [ "$MENU" == "4" ]; then
#   echo "To link SSH"
#   echo ""
#   echo "run ssh-keygen"
#   echo ""
#   echo ssh-copy-id username@remote_host
#
# elif [ "$MENU" == "5" ]; then
# 	GIT_PUSH_PULL $DOTFILES
# fi
