#!/bin/bash

source ./scripts/functions

MAIN_MENU=("Git" "FirstRun" "Link SSH" "Gen SSH")
PRINT_MENU  "MainMenu" "${MAIN_MENU[@]}"
read -p "What will it be?: " MENU_CHOICE

if  [ $MENU_CHOICE == "1" ]; then

#	GIT_PUSH_PULL $DOTFILES
  GI

elif [ "$MENU_CHOICE" == "2" ]; then

  SERVER_INIT

elif [ "$MENU_CHOICE" == "3" ]; then

  bash scripts/link-ssh

elif [ "$MENU_CHOICE" == "4" ]; then

  echo "To link SSH"
  echo ""
  echo "run ssh-keygen"
  echo ""
  echo ssh-copy-id username@remote_host

fi

