#!/bin/bash

# Paths 
REPO='/home/kd/repos/.server-tools-new'
BA='/home/kd/.bash_aliases'
BASERVER='/home/kd/.bash_aliases_server'
BACLIENT='/home/kd/.bash_aliases_client'

TM='/home/kd/.tmux.conf'
ZH='/home/kd/.zshrc'
VM='/home/kd/.vimrc'
HOME='/home/kd'

# Funcs 
function GITPULL () {
  cd $REPO && \
  git pull && \
  yes | cp -f $REPO/dotfiles/$1 $2 && \
  echo "|Pull|>--- $REPO ---> $2 ---<||"
}

function GITPUSH () {
  yes | cp -f $1 $REPO/dotfiles && \
  cd $REPO && \
  git add . && \
  git commit -m "pushed $1 " && \
  git push && \
  echo "|Push|>--- $1 ---> $REPO/dotfiles ---<||"
}

# Main 

clear
echo '||===================|'
echo '||---GIT PULL/PUSH---|'
echo '||===================|'
echo '||-----[1] PUSH------|'
echo '||-----[2] PULL------|'
echo '||-----[3] SHOW------|'
echo '||-----[4] FIRSTRUN--|'
echo '||===================|'

read localorrepo

if  [ $localorrepo == "1" ]; then
  clear
  echo '||===========================|'
  echo '||------GIT PULL/PUSH--------|'
  echo '||===========================|'
  echo '||------[1] Bash Aliases-----|'
  echo '||------[2] Tmux Conf--------|'
  echo '||------[3] Zshrc------------|'
  echo '||------[4] Vimrc------------|'
  echo '||===========================|'
  read file

  if [ $file == "1" ]; then
    GITPUSH $BA
    GITPUSH $BASERVER    
  elif [ $file == "2" ]; then
    GITPUSH $TM
  elif [ $file == "3" ]; then
    GITPUSH $ZH
  elif [ $file == "4" ]; then
    GITPUSH $VM
  fi

  exit 1
elif [ "$localorrepo" == "2" ]; then
  clear
  echo '||===========================|'
  echo '||------GIT PULL/PUSH--------|'
  echo '||===========================|'
  echo '||------[1] Bash Aliases-----|'
  echo '||------[2] Tmux Conf--------|'
  echo '||------[3] Zshrc------------|'  
  echo '||------[4] Vimrc------------|'  
  echo '||===========================|'
  read file

  if [ $file == "1" ]; then
    GITPULL '.bash_aliases' $HOME
    GITPULL '.bash_aliases_server' $HOME    
  elif [ $file == "2" ]; then
    GITPULL '.tmux.conf' $HOME
  elif [ $file == "3" ]; then
    GITPULL .'zshrc' $HOME
  elif [ $file == "4" ]; then
    GITPULL '.vimrc' $HOME
  fi

  exit 1

elif [ "$localorrepo" == "3" ]; then
  if [ $file == "1" ]; then
    sudo nano $BASERVER
  elif [ $file == "2" ]; then 
    sudo nano $TM
  elif [ $file == "3" ]; then
    sudo nano $ZH
  elif [ $file == "4" ]; then
    sudo nano $VM
  fi

elif [ "$localorrepo" == "4" ]; then
  sudo bash firstrun
  GITPULL '.bash_aliases' $HOME
  GITPULL '.bash_aliases_server' $HOME    
  GITPULL '.tmux.conf' $HOME
  GITPULL .'zshrc' $HOME
  GITPULL '.vimrc' $HOME

  exit 1
fi
