
Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.

  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "peru/ubuntu-18.04-server-amd64"
  config.vm.box_version = "20191202.01"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 4200, host: 4200
  config.vm.network "forwarded_port", guest: 3333, host: 3333

  # config.vm.network "public_network"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "3024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision "file", source: "./dotfiles/.aliases", destination: ".aliases"
  config.vm.provision "file", source: "./dotfiles/.gitconfig", destination: ".gitconfig"
  config.vm.provision "file", source: "./dotfiles/.xmodmap", destination: ".xmodmap"
  config.vm.provision "file", source: "./dotfiles/.xbindkeysrc", destination: ".xbindkeysrc"
  config.vm.provision "file", source: "./dotfiles/.tmux.conf", destination: ".tmux.conf"

  config.vm.synced_folder "C:\\Users\\kensl\\repos", "/home/vagrant/repos"
  config.vm.provision :shell, :privileged => false, :path => "bootstrap_dev_server.sh"

  config.vm.provision "file", source: "./dotfiles/.zshrc", destination: ".zshrc"
  config.vm.provision "file", source: "C:\\Users\\kensl\\.ssh\\id_rsa.pub", destination: "~/.ssh/me.pub"

end
