#!/bin/bash

# --------------------------------------- MENU FUNCS

  function PRINT_DIR () {
    # API | $1 = DIR "

    dflist=(`ls -a ${1}`)
    unset dflist[1]

    INDEX=0
    for file in "${dflist[@]}"; do
      if [ $INDEX != 0 ]; then
        echo "$INDEX $file"
      fi
      let INDEX=${INDEX}+1
    done

  }

  function PRINT_MENU () {
    # API | $1 = Menu , $2 = Menu Array

    MENU_TITLE $1
    MENU_ARR=( "$@" )
    unset MENU_ARR[0]

    INDEX=1
    for file in "${MENU_ARR[@]}"; do
      echo "$INDEX $file"
      let INDEX=${INDEX}+1
    done
    echo ""

  }

  function MENU_TITLE () {

    echo ""
    echo "#============================"
    echo "# ${1}"
    echo "#============================"
    echo ""

  }

  function MULTI_MENU () {
    # customize with your own.
    options=("$@")

    menu() {
        echo "Avaliable options:"
        for i in ${!options[@]}; do
            printf "%3d%s) %s\n" $((i+1)) "${choices[i]:- }" "${options[i]}"
        done
        [[ "$msg" ]] && echo "$msg"; :
    }

    MENU_TITLE $1
    prompt="Check an option (again to uncheck, ENTER when done): "
    while menu && read -rp "$prompt" num && [[ "$num" ]]; do
        clear

        MENU_TITLE $1
        [[ "$num" != *[![:digit:]]* ]] &&
        (( num > 0 && num <= ${#options[@]} )) ||
        { msg="Invalid option: $num"; continue; }
        ((num--)); msg="${options[num]} was ${choices[num]:+un}checked"
        [[ "${choices[num]}" ]] && choices[num]="" || choices[num]="+"
    done

    #  printf "You selected"; msg=" nothing"
    for i in ${!options[@]}; do
        [[ "${choices[i]}" ]] && { APP_INSTALLS "${options[i]}"; }
    done
    echo "$msg"
  }


