#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$DIR/../lib/functions"
source "$DIR/./installs"

cd $CURRENT_DIR

# ------------------------------------------------------ INIT

  clear
  CURRENT_DIR=($pwd)

  cd $HOME

  INSTALL_LOG=()


# ------------------------------------------------------ MENU

  function MULTI_MENU () {
    # customize with your own.
    options=("$@")

    menu() {
        echo "Avaliable options:"
        for i in ${!options[@]}; do
            printf "%3d%s) %s\n" $((i+1)) "${choices[i]:- }" "${options[i]}"
        done
        [[ "$msg" ]] && echo "$msg"; :
    }

    MENU_TITLE $1
    prompt="Check an option (again to uncheck, ENTER when done): "
    while menu && read -rp "$prompt" num && [[ "$num" ]]; do
        clear

        MENU_TITLE $1
        [[ "$num" != *[![:digit:]]* ]] &&
        (( num > 0 && num <= ${#options[@]} )) ||
        { msg="Invalid option: $num"; continue; }
        ((num--)); msg="${options[num]} was ${choices[num]:+un}checked"
        [[ "${choices[num]}" ]] && choices[num]="" || choices[num]="+"
    done

  #  printf "You selected"; msg=" nothing"
    for i in ${!options[@]}; do
        [[ "${choices[i]}" ]] && { APP_INSTALLS "${options[i]}"; }
    done
    echo "$msg"
  }

  MENU_OPTS=("zsh" "fzf" "nvm" "aliases" "tmux" "vim" "docker")

  MULTI_MENU "App_Installer" "${MENU_OPTS[@]}"

  DISPLAY_ALERT

